[pytest]
; DJANGO_SETTINGS_MODULE = core.settings
DJANGO_SETTINGS_MODULE = core.test_settings
python_files = tests.py test_*.py *_test.py *_tests.py
python_classes = Test*
python_functions = test_*
norecursedirs = .* build dist venv node_modules
pythonpath = .
addopts = -ra -s

; addopts =
; -ra → show summary of skipped/failed tests
; -q → quieter output
; -s → Show print output
; -x → Fail fast (stop on first failure)


