"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()


def env_bool(name, default=False):
    """Read a boolean environment variable with strict validation."""
    value = os.environ.get(name)
    if value is None:
        return default

    normalized_value = value.strip().lower()
    if normalized_value in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized_value in {'0', 'false', 'no', 'off'}:
        return False

    raise ImproperlyConfigured(
        f'{name} must be one of: true, false, 1, 0, yes, no, on, off.'
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    default='django-insecure-@#x5h3zj!g+8g1v@2^b6^9$8&f1r7g$@t3v!p4#=g0r5qzj4m3',
)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', default='localhost').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS', default='http://localhost:4200'
).split(',')

FRONTEND_URL = os.environ.get(
    'FRONTEND_URL',
    default='http://127.0.0.1:5500',
).rstrip('/')
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        default=FRONTEND_URL,
    ).split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = (
    env_bool('CORS_ALLOW_CREDENTIALS', default=True)
)
BACKEND_URL = os.environ.get(
    'BACKEND_URL',
    default='http://127.0.0.1:8000',
).rstrip('/')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_admin_contexts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_rq',
    'drf_spectacular',
    'auth_app.apps.AuthAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', default='videoflix_db'),
        'USER': os.environ.get('DB_USER', default='videoflix_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', default='supersecretpassword'),
        'HOST': os.environ.get('DB_HOST', default='db'),
        'PORT': os.environ.get('DB_PORT', default=5432),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_LOCATION', default='redis://redis:6379/1'),
        'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
        'KEY_PREFIX': 'videoflix',
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': os.environ.get('REDIS_HOST', default='redis'),
        'PORT': os.environ.get('REDIS_PORT', default=6379),
        'DB': os.environ.get('REDIS_DB', default=0),
        'DEFAULT_TIMEOUT': 900,
        'REDIS_CLIENT_KWARGS': {},
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.'
        'password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', default='localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', default=25))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', default='False').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', default='False').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    default='webmaster@localhost',
)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'auth_app.api.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.environ.get('JWT_ACCESS_TOKEN_MINUTES', default=5))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.environ.get('JWT_REFRESH_TOKEN_DAYS', default=7))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.environ.get('JWT_SIGNING_KEY', default=SECRET_KEY),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': False,
}

JWT_ACCESS_COOKIE_NAME = 'access_token'
JWT_REFRESH_COOKIE_NAME = 'refresh_token'
JWT_COOKIE_HTTPONLY = True
JWT_COOKIE_SECURE = env_bool('JWT_COOKIE_SECURE', default=not DEBUG)
JWT_COOKIE_SAMESITE = os.environ.get('JWT_COOKIE_SAMESITE', default='Lax').title()
JWT_COOKIE_DOMAIN = os.environ.get('JWT_COOKIE_DOMAIN') or None
JWT_ACCESS_COOKIE_PATH = '/'
JWT_REFRESH_COOKIE_PATH = os.environ.get(
    'JWT_REFRESH_COOKIE_PATH',
    default='/api/',
)

if JWT_COOKIE_SAMESITE not in {'Lax', 'Strict', 'None'}:
    raise ImproperlyConfigured(
        'JWT_COOKIE_SAMESITE must be one of: Lax, Strict, None.'
    )
if JWT_COOKIE_SAMESITE == 'None' and not JWT_COOKIE_SECURE:
    raise ImproperlyConfigured(
        'JWT_COOKIE_SECURE must be true when JWT_COOKIE_SAMESITE is None.'
    )

# JavaScript must be able to read the CSRF cookie and mirror its value in the
# X-CSRFToken header. JWT cookies themselves remain inaccessible to scripts.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=JWT_COOKIE_SECURE)
CSRF_COOKIE_SAMESITE = os.environ.get(
    'CSRF_COOKIE_SAMESITE',
    default=JWT_COOKIE_SAMESITE,
).title()

if CSRF_COOKIE_SAMESITE not in {'Lax', 'Strict', 'None'}:
    raise ImproperlyConfigured(
        'CSRF_COOKIE_SAMESITE must be one of: Lax, Strict, None.'
    )
if CSRF_COOKIE_SAMESITE == 'None' and not CSRF_COOKIE_SECURE:
    raise ImproperlyConfigured(
        'CSRF_COOKIE_SECURE must be true when CSRF_COOKIE_SAMESITE is None.'
    )

JAZZMIN_SETTINGS = {
    'site_title': 'DA & Olivier Videoflix Admin',
    'site_header': 'DA & Olivier Videoflix Administration',
    'site_brand': 'DA & Olivier Videoflix',
    'welcome_sign': 'Welcome to DA & Olivier Videoflix Admin',
    'copyright': 'DA & Olivier Lowe',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'videoflix API Endpoint Dokumentation',
    'DESCRIPTION': 'Videoflix ist eine eigenständig entwickelte '
    'Videostreaming-Plattform im Stil von Netflix.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'Authentication', 'description': 'Login und Registrierung'},
        {
            'name': 'Video',
            'description': 'Videoanzeige, Streaming und Segmentbereitstellung',
        },
    ],
    'SWAGGER_UI_SETTINGS': {
        'docExpansion': 'list',  # or "full"
        'tagsSorter': 'none',
        'operationsSorter': 'none',
        # docExpansion = "none"  # closed
        # docExpansion = "list"  # only operations visible
        # docExpansion = "full"  # everything opened
    },
    'SORT_OPERATIONS': True,
    # OTHER SETTINGS
}
